### ISSUE TITLE
_config.yml issue

### ISSUE THREAD

**Issue by nimeso** [bluehousegroup/silverstripe-data-object-version-viewer#2]
DataObject:  
  extensions:  
    - VersionViewerExtension

should be

DataObject:  
  extensions:  
    - VersionViewerDataObject

**Comment by andrewvt** [comment]
You don't actually have to add extra yml for this module to work anymore.  That part of the documentation in the README.md was old.  We have removed it.  Sorry for any confusion.

Note, that you do have to turn versioning on for your DataObject in your yml as discussed in #3.
