### ISSUE TITLE
"hasExtension" check is limiting

### ISSUE THREAD

**Issue by adrexia** [bluehousegroup/silverstripe-data-object-version-viewer#5]
$this->owner->hasExtension('Versioned') will return false if an object has a subclass of the versioned extension instead of the original. This can happen if used alongside this versioned-dataobjects module: 

https://github.com/heyday/silverstripe-versioneddataobjects

Is there another check that could be used instead?

**Comment by andrewvt** [comment]
$this->owner->hasExtension('Versioned') is a standard check for versioning that appears elsewhere in the SilverStripe core.  I'm not aware of another method for checking, but if anyone else does please let us know.

For now we would like to support the silverstripe-versioneddataobjects module as well in hopes that it will plug some of the gaps with versioned dataobjects in the core and betterbuttons.

If you can confirm that changing that line to what is below addresses the issue I'll be happy to commit the change:

if($this->owner->hasExtension('Versioned') || $this->owner->hasExtension('VersionedDataObject')) {

**Comment by adrexia** [comment]
Yes, that works

**Comment by andrewvt** [comment]
That change is committed.  Let me know if you need anything else for now.  Thanks!

**Comment by adrexia** [comment]
Thanks!
