### ISSUE TITLE
Composer name doesn't match required css path

### ISSUE THREAD

**Issue by adrexia** [bluehousegroup/silverstripe-data-object-version-viewer#7]
When installing via composer the project name, as taken from the composer file, is silverstripe-data-object-version-viewer, however the yml file is trying to require css as: 'data_object_version_viewer/css/styles.css'.

I'm not sure whether it would be better to change the css path, or rename the project in composer to match the shorter module name. For now, I've been including the correct css in my own project.

**Comment by irkeepin** [comment]
Thanks @adrexia and sorry for the delay. I've updated the css path in config.yml.

**Comment by adrexia** [comment]
Thanks!
